name: "Sync GHAS to Jira"

on:
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes
  workflow_dispatch:
    

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_url: 'https://devtoolsindia.atlassian.net/'
          jira_user: 'tejaswinid@devtools.in'
          jira_token: 'L4EWhljc4pajQit3j6Wo910A'
          jira_project: 'DE'
          github_token: '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'
          sync_direction: 'gh2jira'
